### ISSUE TITLE
Filtering with precomputed roll, pitch, and yaw

### ISSUE THREAD

**Issue by SquirrelKnight** [toshiharutf/Kalman_Filter_GNS_INS#1]
Hello,

I am attempting to apply the Kalman filter to data from a wave glider. imu_gyro rotational speeds are not provided in the available data, however, the unit computes roll, pitch, and yaw. Would you be able to recommend a method of running the filter given this prior information? I have made some attempts at doing so myself, but I am not sure how deeply embedded the imu_gyro values are in the rest of the filter computations.

Thank you for your time and I appreciate your response!

**Comment by toshiharutf** [comment]
In this repo there are two filters. Not sure to which one you are referring. I will try to explain for both.
A Kalman filter has two phases:

Prediction
Update

Prediction could be done using a system model to "predict" or simulate the next state of the system. For the INS filter, I'm using the gyro info to predict the next attitude of the system. Therefore, without gyro info, the filter is pretty much useless, because the acceleration data alone is very noisy to provide good results.

For the INS/GNSS filter, taking out the gyro info will probably also have detrimental results.

If you want to make a simple test, just comment the parts where the gyro info is used in the prediction step and observe how much the output deviates from the actual sensor measurements.

**Comment by SquirrelKnight** [comment]
I am most interested in using the INS/GNSS filter. Upon further digging, it looks like I can extract some additional data from my INS instrument (an EPSON G320 INS) logs, which has north, east, and up velocity. I imagine that would convert to x, y, and -z (assuming we want to use NED coordinates).

I am not sure if these would be appropriate for input into the filter. If you don't mind looking, these are the parameters.
<img width="1263" alt="Screen Shot 2022-06-03 at 6 55 15 PM" src="https://user-images.githubusercontent.com/41596863/171972210-d30f15b7-b9cd-4c35-83f3-417ca50ac6d0.png">

The acceleration and magnetic bearing come from a different instrument (an XSENS MTi-300), which has slightly different timing. I imagine I would also need to interpolate to match timestamps from the INS data.

**Comment by toshiharutf** [comment]
So, it seems that your device already provides the roll, pitch, and yaw. So possibly there are some calculations already going on. Check if your device has some filters internally also.
For my filter, the raw IMU data is the input, and you get from that the r,p, y.

**Comment by SquirrelKnight** [comment]
The position is is provided for the INS data, as well as from the GNSS
antenna. I have performed some post-processing on the GNSS data to improve
the initial locations using RTKLIB and want to integrate the INS data to
help smooth the locations (particularly for when satellites are dropped).
The exact details of what filtering is being performed on the INS is not
given by the provider.

In this case, it seems I would need to develop a new filter (using either
roll, pitch, and yaw or the INS positions), however, my experience with
developing filters is amateur-ish to say the least!

**Comment by toshiharutf** [comment]
Yes, the filter you find here is oriented more towards bare sensors like IMU, and GNSS independently. I'm not sure, but it could be possible that your sensor is already doing some sort of dead-reckoning when the GNSS signal is not avaiable. But it is hard to know, unless the manufacturer gives you that info.

You could try some tests with your sensor if that is the case. Cover the antenna with some metal plating and walk around (perhaps in a squre pattern to ease the tracking). If you see that the recording has some tracking of the position, perhaps the sensor internally is running a dead-reckoning algorithm using only the IMU, possibly using also their own Kalman filter implementation.

**Comment by SquirrelKnight** [comment]
After a lot of digging I was able to find raw acceleration and gyro measures (tucked away in some binary files).

Now that I have the data, I have applied instrument corrections to the raw data and it should be ready for filtering. My final question is this; there are certain times where there is not data from the IMU, and other times when data is not available from the GNSS antenna. I'm assuming that the code doesn't account for times when only some of the data available, but was wondering if you thought this would be trivial to implement, or if it is something that would be too difficult?

Once again, thank you for your candid response, and I appreciate your time.

**Comment by toshiharutf** [comment]
The filter does account for missed measurements.

Like here (line 312): 
` # new GNSS measurement
        if row["gnss_new_data"]:`

when there is no new data, the filter just compute the prediction step.
However, this filter assumes that the IMU always provides data. You may chose to change that.

I hope the info has been helpful. I will close the ticket.
